{
    "_links": {
        "self": {
            "href": "/data?metrics=DAD,ARPD&startDay==14DaysAgo&endDay=today&dimensions=day,Platform&sort=day,Platform"
        }
    },
    "columns": {
        "day": {
            "name": "day",
            "displayName": "date",
            "dataType": "ISOdatetime",
            "format:": "YYYY-MM-DDTHH:mm:ssZ",
            "unit": "",
            "type": "dimension",
            "colIndex": 0
        },
        "Platform": {
            "name": "Platform",
            "displayName": "Platform",
            "dataType": "String",
            "format": "s",
            "unit": "",
            "type": "dimension",
            "colIndex": 1
        },
        "DAD": {
            "name": "DAD",
            "displayName": "Active Devices",
            "dataType": "Number",
            "format": "d",
            "unit": "devices",
            "type": "metric",
            "colIndex": 2
        },
        "ARPD": {
            "name": "ARPD",
            "displayName": "Average Revenue Per Device",
            "dataType": "Number",
            "format": "f",
            "unit": "$",
            "type": "metric",
            "colIndex": 3
        }
    },
    "rows": [
        ["2014-02-10T00:00:00Z", "Android", 1003921, 6.34],
        ["2014-02-10T00:00:00Z", "iPhoneOS", 1009045, 6.74],
        ["2014-02-11T00:00:00Z", "Android", 1000896, 4],
        ["2014-02-11T00:00:00Z", "iPhoneOS", 1009722, 4.3],
        ["2014-02-12T00:00:00Z", "Android", 1002642, 4.34],
        ["2014-02-12T00:00:00Z", "iPhoneOS", 1007851, 4.64],
        ["2014-02-13T00:00:00Z", "Android", 1007872, 4.65],
        ["2014-02-13T00:00:00Z", "iPhoneOS", 1004693, 4.45],
        ["2014-02-14T00:00:00Z", "Android", 1004079, 3.45],
        ["2014-02-14T00:00:00Z", "iPhoneOS", 1002435, 3.25],
        ["2014-02-15T00:00:00Z", "Android", 1006457, 4.45],
        ["2014-02-15T00:00:00Z", "iPhoneOS", 1009690, 4.35],
        ["2014-02-16T00:00:00Z", "Android", 1004259, 2.1],
        ["2014-02-16T00:00:00Z", "iPhoneOS", 1003031, 1.8],
        ["2014-02-17T00:00:00Z", "Android", 1009039, 2],
        ["2014-02-17T00:00:00Z", "iPhoneOS", 1008991, 2.2],
        ["2014-02-18T00:00:00Z", "Android", 1009877, 3.00],
        ["2014-02-18T00:00:00Z", "iPhoneOS", 1009957, 3.01],
        ["2014-02-19T00:00:00Z", "Android", 1007400, 2.2],
        ["2014-02-19T00:00:00Z", "iPhoneOS", 1003673, 2.3],
        ["2014-02-20T00:00:00Z", "Android", 1001811, 3.4],
        ["2014-02-20T00:00:00Z", "iPhoneOS", 1002642, 3.64],
        ["2014-02-21T00:00:00Z", "Android", 1004202, 4.5],
        ["2014-02-21T00:00:00Z", "iPhoneOS", 1004876, 4.25],
        ["2014-02-22T00:00:00Z", "Android", 1008903, 4.3],
        ["2014-02-22T00:00:00Z", "iPhoneOS", 1002498, 4.13],
        ["2014-02-23T00:00:00Z", "Android", 1001201, 4.33],
        ["2014-02-23T00:00:00Z", "iPhoneOS", 1009236, 4.23],
        ["2014-02-24T00:00:00Z", "Android", 1002031, 2.1],
        ["2014-02-24T00:00:00Z", "iPhoneOS", 1004370, 2.11]
    ]
}